### PR TITLE
Galois Field minor improvements.

### PR DESCRIPTION
**Pull request by rafaelmcam**
Hello, thanks for the development of this project.

I was thinking about implementing some linear block codes that I think should be a good addition for the project: Hamming, BCH, ReedSolomon, Reed-Muller, SoftDecision techniques for algebraic codes.

I started looking for the current GaloisField implementation and I initially didn't quite understand the input form for the elements since most projects represent Galois elements by it power form (element alpha^5 in GF(8) is represented by integer "5"), which should have more than one benefit for this kind of representation in terms of performance and usability. For instance, the __mul__ operation can be done simple as a sum mod (2^m - 1) in power form.

I'm opening a draft pull request to discuss following points:

- User can input GF elements as power form elements. This facilitates __mul__ operation and complicate the addition (should convert elements to tuple form before addition).
- As things currently are in this draft pull request the GF class is still representing the elements internally in tuple form. In the test case for closure this still can represent a slight speed performance boost even though I'm converting power(user input)->tuple(__init__ method)->power(__mul__ method).
- Maybe we should represent elements internally in power form only, or at least give the user the option to directly input elements in this form without needing to declare a GF class just to use the power_to_tuple method, extract the elements and declare another GF class.
- Some minor additions like __eq__ and __repr__ should also be handy.

Looking forward to discuss possible changes to the GF class and your opinion on the possible addition of more linear block codes and techniques.

### CODE REVIEW

**Comment by BastienTr** [comment]
Hi @rafaelmcam,

Thanks for your interest in this project! I don't have any precise advice for the GF class, as I've never had a close look to it. @veeresht do you have some time to look at this draft PR ? If not, I could try to look more in-depth on this topic.

Regarding the addition of new linear block codes and techniques, I don't see any reason to say something else that "great idea." As long as it is in Python and that it is related to communications, any new addition is welcome!

**Comment by veeresht** [comment]
@rafaelmcam  Thanks for this PR. I completely understand your motivation to provide another power based representation of Galois field elements. I skimmed through your PR and looks pretty good. Can you make this into an actual PR (instead of a draft). I will go through it more thoroughly and merge it. Thanks for your contribution again! :+1:  

As for adding other linear block code implementations, that's a great idea as @BastienTr  mentioned. As a starting point I do have function to generate all the cyclic code generator polynomials which I hope will be useful for a BCH & RS code implementation.  https://github.com/veeresht/CommPy/blob/master/commpy/channelcoding/algcode.py#L11

**Comment by rafaelmcam** [comment]
@veeresht @BastienTr Thanks for the feedback, I opened the draft PR. For now the PR is only intended to be an easier way of defining the elements directly, probably there is considerable room for performance improvements. I think we should in the future change the way the operations are done with some implementation tricks ([A](https://en.wikipedia.org/wiki/Finite_field_arithmetic#Implementation_tricks) or [B](https://en.wikipedia.org/wiki/Zech%27s_logarithm)) if the performance turn out to be indeed a bottleneck.

**Comment by veeresht** [comment]
@rafaelmcam There seems to some error in the PR. Could you take a look and fix it? You can click on the travis-ci details to get to the build and test log.

**Comment by rafaelmcam** [comment]
@veeresht I'll look into it, I used a python 3.6 feature (F-String), will change to the pre3.6 approach.

**Comment by rafaelmcam** [comment]
@veeresht Just saw that the syntax feature was not the only thing tests were failing.

The cosets method for GF class is looping forever and the tests timed out. I found the problem to be one change in convention that I made in tuple_to_power method converting the element in tuple form "0" to "-1" since I was using this convention (0 (power form) == 1 (tuple form)).

Master branch is using the convention tuple form "0" is power form "0" from what I understand, should this be intended behaviour? If I'm not getting things wrong this should mean that there are two elements in tuple form which are being mapped to the same representation "0" in power form, which should be a problem.

I'm a bit confused with the mappings right now so I'll redo my PR and investigate the master branch implementation further.

**Pull request closed without merging**
